
#ifndef BENJAMINRECOMBRATESDATALOCATION_HPP
#define BENJAMINRECOMBRATESDATALOCATION_HPP

#define BENJAMINRECOMBDATALOCATION "/Users/meg/Desktop/PhD/newcmac/CMacIonize/src/data/benjamin_rrrates/"

#endif // BENJAMINRECOMBRATESDATALOCATION_HPP
