
#ifndef CHIANTIRECOMBRATESDATALOCATION_HPP
#define CHIANTIRECOMBRATESDATALOCATION_HPP

#define CHIANTIRECOMBDATALOCATION "/Users/meg/Desktop/PhD/newcmac/CMacIonize/src/data/chianti_rrates/"

#endif // CHIANTIRECOMBRATESDATALOCATION_HPP
