/*******************************************************************************
 * This file is part of CMacIonize
 * Copyright (C) 2016 Bert Vandenbroucke (bert.vandenbroucke@gmail.com)
 *
 * CMacIonize is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CMacIonize is distributed in the hope that it will be useful,
 * but WITOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CMacIonize. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

/**
 * @file CompilerInfo.cpp
 *
 * @brief Information about the program version and compiler that is configured
 * by CMake.
 *
 * Do not edit this file directly! Instead edit CompilerInfo.cpp.in.
 *
 * @author Bert Vandenbroucke (bv7@st-andrews.ac.uk)
 */
#include "CompilerInfo.hpp"

/// Git specific info

const char CompilerInfo::_git_build_string[] = "";

/// Compilation time info

const uint_least32_t CompilerInfo::_compilation_time_day =
    atoi("25");
const uint_least32_t CompilerInfo::_compilation_time_month =
    atoi("8");
const uint_least32_t CompilerInfo::_compilation_time_year =
    atoi("2025");
const uint_least32_t CompilerInfo::_compilation_time_hour =
    atoi("21");
const uint_least32_t CompilerInfo::_compilation_time_minutes =
    atoi("8");
const uint_least32_t CompilerInfo::_compilation_time_seconds =
    atoi("37");

// Compiler info

const char CompilerInfo::_compiler_name[] = "AppleClang";
const char CompilerInfo::_compiler_version[] = "17.0.0.17000013";

/// Operating system info

const char CompilerInfo::_os_name[] = "Darwin";
const char CompilerInfo::_os_kernel_name[] = "Darwin";
const char CompilerInfo::_os_kernel_release[] = "24.6.0";
const char CompilerInfo::_os_kernel_version[] = "Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64";
const char CompilerInfo::_os_hardware_name[] = "i386";
const char CompilerInfo::_os_host_name[] = "Megs-MacBook-Pro.local";
