/*******************************************************************************
 * This file is part of CMacIonize
 * Copyright (C) 2017 Bert Vandenbroucke (bert.vandenbroucke@gmail.com)
 *
 * CMacIonize is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CMacIonize is distributed in the hope that it will be useful,
 * but WITOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CMacIonize. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

/**
 * @file ConfigurationInfo.cpp
 *
 * @brief File containing CMake configured configuration flags.
 *
 * Do not edit this file directly! Instead edit ConfigurationInfo.cpp.in.
 *
 * @author Bert Vandenbroucke (bv7@st-andrews.ac.uk)
 */
#include "ConfigurationInfo.hpp"

// clang-format off
const std::string ConfigurationInfo::_configuration_option_keys
    [CONFIGURATION_OPTIONS_NUMBER] = {"HAVE_WINDOWS","HAVE_POSIX","HAVE_GSL","USE_LOCKFREE","DO_OUTPUT_COOLING","DO_OUTPUT_HEATING","DO_OUTPUT_PHOTOIONIZATION_RATES","DEBUG_BUILD","HAVE_HDF5","MAX_NUM_THREADS","HAVE_OPENMP","HAVE_MPI","HAVE_PYTHON","HAVE_MULTIPRECISION","HAVE_FAST_MATH","HAVE_VECTORIZATION","HAVE_ASSERTIONS","HAVE_OUTPUT_CYCLES","HAVE_PRECISE_INTEL_FLOATS","HAVE_HYDROGEN_ONLY","VARIABLE_ABUNDANCES","ADDITIONAL_COOLANTS",};
const std::string ConfigurationInfo::_configuration_option_values
    [CONFIGURATION_OPTIONS_NUMBER] = {"False","True","False","False","False","False","False","False","True","8","False","False","False","True","False","False","False","False","False","False","False","False",};
// clang-format on
